import { extractSqlVerb } from '../performance/measure.js';
import { beginOutboundSpan, endOutboundSpan, type OutboundSpanStart } from '../core/tracing.js';
import type { StackTracePlugin } from '../core/plugins/types.js';
import { safeRun } from '../core/safe-run.js';

/**
 * Knex / Lucid connection that supports the `query`, `query-response` and `query-error` events.
 */
export type LucidDatabaseLike = {
  on(event: 'query', callback: (query: unknown) => void): unknown;
  on(event: 'query-response', callback: (response: unknown, query: unknown) => void): unknown;
  on(event: 'query-error', callback: (error: unknown, query: unknown) => void): unknown;
};

/**
 * O serviço `db` do Lucid (`import db from '@adonisjs/lucid/services/db'`). Ele NÃO emite os eventos do
 * knex: é um gerente de conexões, e cada conexão tem o próprio knex (`client`, e `readClient` quando há
 * réplica). Tipado frouxo de propósito: o `Database` real do Lucid 20 a 22 precisa ser atribuível a ele.
 * O `emitter` fica fora do tipo: o Lucid o declara `private` (só no TypeScript), e com ele no tipo o
 * `Database` real deixava de ser atribuível (TS2345). Em runtime ele existe e é lido por {@link LucidEmitter}.
 */
export type LucidDatabaseServiceLike = {
  manager: { connections: { values(): Iterable<unknown> } };
};

/** O emissor do serviço `db` (`db:connection:connect`), lido em runtime — ver {@link LucidDatabaseServiceLike}. */
type LucidEmitter = { on(event: string, listener: (connection: unknown) => void): unknown };

/**
 * Fields knex puts on the `query` / `query-response` / `query-error` event payloads.
 * `__knexQueryUid` is the per-query id used to pair the start and completion events;
 * autogenerated notifications (e.g. BEGIN/COMMIT, mssql SAVE TRANSACTION) carry no uid
 * and no completion counterpart.
 */
type KnexQueryEvent = {
  __knexQueryUid?: string;
  sql?: string;
  method?: string;
};

type PendingQuerySpan = {
  begin: OutboundSpanStart;
  operationName: string;
  attributes: Record<string, unknown>;
};

/**
 * Upper bound on tracked in-flight queries. Emit paths without a completion event
 * (e.g. knex `.stream()`) must not grow the pending map forever; beyond the cap the
 * oldest entry is dropped and its span is never emitted.
 */
export const MAX_PENDING_LUCID_QUERIES = 1000;

/** Bulk insert pode ter megabytes de SQL; verbo e tabela estão sempre no começo do texto. */
const MAX_SQL_SCAN_CHARS = 8_192;

export type LucidStackTracePluginOptions = {
  /** Real database engine name, e.g. `postgres`, `mysql`, or `sqlserver`. Default: inferred from the driver. */
  dbSystem?: string;
};

/** Driver do knex → engine real. `db_system` é o banco, nunca o ORM. */
const DB_SYSTEM_BY_DRIVER: Readonly<Record<string, string>> = {
  pg: 'postgres',
  postgres: 'postgres',
  postgresql: 'postgres',
  pgnative: 'postgres',
  mysql: 'mysql',
  mysql2: 'mysql',
  mssql: 'sqlserver',
  sqlite: 'sqlite',
  sqlite3: 'sqlite',
  'better-sqlite3': 'sqlite',
  libsql: 'sqlite',
  oracle: 'oracle',
  oracledb: 'oracle',
  redshift: 'redshift',
  cockroachdb: 'cockroachdb',
};

/**
 * Um knex é instrumentado UMA vez, venha de quantos plugins vier: sem réplica o Lucid usa o mesmo knex
 * como `client` e `readClient`, e um `register()` repetido não pode dobrar os spans.
 */
const instrumentedKnex = new WeakSet<object>();

function sanitizeIdentifier(token: string | undefined): string | undefined {
  if (token === undefined) return undefined;
  const cleaned = token.replace(/[,;]/gu, '').replace(/["`[\]]/gu, '');
  const parts = cleaned
    .split('.')
    .map((part) => part.trim())
    .filter(Boolean);
  const last = parts.at(-1);
  if (last === undefined) return undefined;
  return /^[A-Za-z_][A-Za-z0-9_$]*$/u.test(last) ? last : undefined;
}

function tokenAfter(sql: string, marker: string): string | undefined {
  const normalized = sql.replace(/\s+/gu, ' ').trim();
  const index = normalized.toUpperCase().indexOf(marker);
  if (index < 0) return undefined;
  return normalized
    .slice(index + marker.length)
    .trim()
    .split(/\s+/u)[0];
}

function inferTable(sql: string | undefined, verb: string | undefined): string | undefined {
  if (sql === undefined || verb === undefined) return undefined;
  if (verb === 'SELECT') return sanitizeIdentifier(tokenAfter(sql, ' FROM '));
  if (verb === 'INSERT') return sanitizeIdentifier(tokenAfter(sql, ' INTO '));
  if (verb === 'UPDATE') return sanitizeIdentifier(tokenAfter(sql, 'UPDATE '));
  if (verb === 'DELETE') return sanitizeIdentifier(tokenAfter(sql, ' FROM '));
  if (verb === 'TRUNCATE') return sanitizeIdentifier(tokenAfter(sql, ' TABLE '));
  return undefined;
}

function inferOperationName(verb: string | undefined, table: string | undefined): string {
  const operation = (verb ?? 'QUERY').toLowerCase();
  return table !== undefined ? `Lucid.${table}.${operation}` : `Lucid.${operation}`;
}

function isKnexLike(value: unknown): value is LucidDatabaseLike {
  return (
    (typeof value === 'function' || (typeof value === 'object' && value !== null)) &&
    typeof (value as { on?: unknown }).on === 'function'
  );
}

function isLucidDatabaseService(value: unknown): value is LucidDatabaseServiceLike {
  if (typeof value !== 'object' || value === null) return false;
  const v = value as { manager?: { connections?: { values?: unknown } }; emitter?: { on?: unknown } };
  return typeof v.manager?.connections?.values === 'function' && typeof v.emitter?.on === 'function';
}

function driverName(config: unknown): string | undefined {
  const client = (config as { client?: unknown } | null | undefined)?.client;
  return typeof client === 'string' && client !== '' ? client.toLowerCase() : undefined;
}

function inferDbSystem(knex: object, connectionConfig: unknown): string | undefined {
  const name = driverName(connectionConfig) ?? driverName((knex as { client?: { config?: unknown } }).client?.config);
  return name === undefined ? undefined : (DB_SYSTEM_BY_DRIVER[name] ?? name);
}

/**
 * Emits DB spans for completed queries without sending raw SQL or bindings.
 *
 * Aceita o serviço `db` do Lucid — instrumenta cada conexão, as já abertas e as que o Lucid abrir depois
 * (ele conecta sob demanda, na primeira query) — ou um knex direto. O knex emite `query` antes do
 * statement e `query-response` / `query-error` depois; o span é a janela entre os eventos pareados.
 */
export function createLucidStackTracePlugin(
  database: LucidDatabaseLike | LucidDatabaseServiceLike,
  options: LucidStackTracePluginOptions = {},
): StackTracePlugin {
  return {
    name: 'db-lucid',
    type: 'db',
    init() {
      const pending = new Map<string, PendingQuerySpan>();

      const start = (query: unknown, dbSystem: string): void => {
        const q = query as KnexQueryEvent | null | undefined;
        const uid = q?.__knexQueryUid;
        if (q === null || q === undefined || typeof uid !== 'string' || uid === '') return;
        const begin = beginOutboundSpan();
        if (begin === null) return;
        const sql = typeof q.sql === 'string' ? q.sql.slice(0, MAX_SQL_SCAN_CHARS) : undefined;
        const verb = extractSqlVerb(sql) ?? (q.method !== undefined ? q.method.toUpperCase() : undefined);
        const table = inferTable(sql, verb);
        const operationName = inferOperationName(verb, table);
        pending.set(uid, {
          begin,
          operationName,
          attributes: {
            db_system: dbSystem,
            db_operation: verb ?? operationName,
            ...(table !== undefined ? { db_table: table } : {}),
          },
        });
        if (pending.size > MAX_PENDING_LUCID_QUERIES) {
          const oldest = pending.keys().next().value;
          if (oldest !== undefined) pending.delete(oldest);
        }
      };

      const finish = (query: unknown, err?: Error): void => {
        const uid = (query as KnexQueryEvent | null | undefined)?.__knexQueryUid;
        if (typeof uid !== 'string') return;
        const entry = pending.get(uid);
        if (entry === undefined) return;
        pending.delete(uid);
        endOutboundSpan(entry.begin, {
          name: entry.operationName,
          type: 'db',
          attributes: entry.attributes,
          ...(err !== undefined ? { err } : {}),
        });
      };

      const instrumentKnex = (knex: unknown, connectionConfig?: unknown): void => {
        if (!isKnexLike(knex) || instrumentedKnex.has(knex)) return;
        instrumentedKnex.add(knex);
        const dbSystem = options.dbSystem ?? inferDbSystem(knex, connectionConfig) ?? 'unknown';
        // O knex emite estes eventos de dentro do executor da query: um throw aqui voltaria para a query
        // do cliente. Cada listener é dono da própria falha.
        knex.on('query', (query: unknown) => {
          safeRun('lucid.query', () => start(query, dbSystem));
        });
        knex.on('query-response', (_response: unknown, query: unknown) => {
          safeRun('lucid.queryResponse', () => finish(query));
        });
        knex.on('query-error', (error: unknown, query: unknown) => {
          safeRun('lucid.queryError', () => finish(query, error instanceof Error ? error : new Error(String(error))));
        });
      };

      if (isLucidDatabaseService(database)) {
        const instrumentConnection = (connection: unknown, config?: unknown): void => {
          const c = connection as { client?: unknown; readClient?: unknown; config?: unknown } | null | undefined;
          instrumentKnex(c?.client, config ?? c?.config);
          instrumentKnex(c?.readClient, config ?? c?.config);
        };
        // As conexões já abertas...
        for (const node of database.manager.connections.values()) {
          const n = node as { connection?: unknown; config?: unknown } | null | undefined;
          instrumentConnection(n?.connection, n?.config);
        }
        // ...e as que o Lucid abrir depois.
        const { emitter } = database as unknown as { emitter: LucidEmitter };
        emitter.on('db:connection:connect', (connection: unknown) => {
          safeRun('lucid.connect', () => instrumentConnection(connection));
        });
        return;
      }
      if (isKnexLike(database)) {
        instrumentKnex(database);
        return;
      }
      throw new TypeError(
        'cc-stacktracer/db-lucid: expected the Lucid `db` service (@adonisjs/lucid/services/db) or a Knex instance',
      );
    },
  };
}
